version: '3.7'

services:
  api:
    build: .
    container_name: tny.local
    ports:
      - "8888:8080"
    environment:
      - TNY_UI_URL=ui.tny.ie
      - TNY_AUTH_KEY=$AUTH_KEY
      - TNY_SELF_SIGNUP=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=pass123
      - DB_NAME=postgres
      - DEBUG=true
      - SENDGRID_CREDENTIAL=$SENDGRID_CREDENTIAL
    networks:
      backend:

  db:
    container_name: db.tny.local
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
    networks:
      backend:
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8000:8080"
    networks: 
      backend:

networks:
  backend: