version: '3.7'

services:

  api:
    build: .
    container_name: tny-api
    ports:
      - "8888:8080"
    environment:
      - TNY_AUTH_KEY=dudebro
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=pass123
      - DB_NAME=postgres
      - DEBUG=true
      - SENDGRID_CREDENTIAL=${SENDGRID_CREDENTIAL}
    networks: 
      backend:

  db:
    image: postgres
    container_name: tny-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=postgres
    networks:
      backend:

  adminer:
    image: adminer
    ports:
      - "8989:8080"
    networks:
      backend:
networks:
  backend: